export type RegistrationRow = {
  id: string;
  user_id: string;
  competition_slug: string;
  competition_name: string;
  student_name: string;
  student_age: number;
  guardian_name: string;
  guardian_email: string;
  city_country: string;
  entry_fee: string;
  payment_status: "pending" | "payment_created" | "paid" | "failed" | "cancelled";
  razorpay_order_id: string | null;
  razorpay_payment_id: string | null;
  razorpay_signature: string | null;
  payment_amount: number | null;
  payment_currency: string | null;
  paid_at: string | null;
  created_at: string;
};
