import type { AgeProofStatus, PaymentStatus, RegistrationStatus } from "@/lib/payment/status";

export type RegistrationRow = {
  id: string;
  user_id: string;
  competition_slug: string;
  competition_name: string;
  student_name: string;
  student_age: number;
  guardian_name: string;
  guardian_email: string;
  city: string | null;
  country: string | null;
  city_country: string;
  entry_fee: string;
  registration_status: RegistrationStatus | null;
  age_proof_status: AgeProofStatus | null;
  payment_required: boolean | null;
  payment_status: PaymentStatus;
  payment_provider: string | null;
  payment_order_id: string | null;
  payment_id: string | null;
  razorpay_order_id: string | null;
  razorpay_payment_id: string | null;
  razorpay_signature: string | null;
  amount_due: number | null;
  amount_paid: number | null;
  points_redeemed: number | null;
  points_discount_amount: number | null;
  payment_amount: number | null;
  payment_currency: string | null;
  seat_confirmed_at: string | null;
  paid_at: string | null;
  created_at: string;
  updated_at: string | null;
};
